### ISSUE TITLE
Script fails if --docker-image is specified

### ISSUE THREAD

**Issue by GJL** [zalando/planb-cassandra#66]
`create_cluster.py` fails if a docker image is specified with the `--docker-image` parameter.
For example,

```
./create_cluster.py --cluster-name cassandra-test  --docker-image registry.opensource.zalan.do/stups/planb-cassandra:cd60  --internal eu-central-1
```

Output
```
[...]
Traceback (most recent call last):
  File "./create_cluster.py", line 648, in <module>
    cli()
  File "/Users/gyao/.pyenv/versions/3.5.0/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gyao/.pyenv/versions/3.5.0/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/gyao/.pyenv/versions/3.5.0/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gyao/.pyenv/versions/3.5.0/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./create_cluster.py", line 620, in cli
    user_data = generate_taupage_user_data(locals())
  File "./create_cluster.py", line 341, in generate_taupage_user_data
    'application_version': version,
UnboundLocalError: local variable 'version' referenced before assignment
```

The script tries to set the latest docker image tag as the `application_version`. However, when `--docker-image` is specified, the version should be parsed from the passed command line argument.

**Comment by a1exsh** [comment]
Do we still have to put this `application_version` in the user data?  Maybe the fix would be to remove it altogether.

**Comment by a1exsh** [comment]
#70 takes care of this
